### PR TITLE
Update Store.js

### PR DESCRIPTION
**Pull request by Zytekaron**
Get rid of that spread op into array

### CODE REVIEW

**Comment by IceeMC** [comment]
Spreading the array is needed or else it wouldn’t return an array, it would just return a MapIterator which isn’t a goddam array

**Comment by IceeMC** [comment]
Also tony don’t merge stupid PR's like these

**Comment by ThatTonybo** [comment]
Oh be quiet, I thought it would help.

**Comment by IceeMC** [comment]
Sorry

**Pull request merged**
